/// Return the Adobe Glyph List name for a Unicode codepoint string (e.g. `"U+0041"`).
///
/// The glyph name is the identifier font editors (Glyphs.app, RoboFont, FontLab, UFO)
/// use to map an image or glyph into a Unicode slot. Output PNG filenames must use
/// this name as their stem for direct import to work.
///
/// Covers Basic Latin, Latin-1 Supplement, and common typographic extras.
/// Anything not listed falls back to `uniXXXX` (BMP) or `uXXXXX` (above BMP),
/// which every major font editor also recognises.
///
/// Reference: <https://github.com/adobe-type-tools/agl-aglfn>
pub fn agl_name(unicode: &str) -> String {
    let cp_str = unicode.trim_start_matches("U+").trim_start_matches("u+");
    let cp = match u32::from_str_radix(cp_str, 16) {
        Ok(v) => v,
        Err(_) => return format!("uni{}", cp_str.to_uppercase()),
    };

    match cp {
        0x0020 => "space".into(),
        0x0021 => "exclam".into(),
        0x0022 => "quotedbl".into(),
        0x0023 => "numbersign".into(),
        0x0024 => "dollar".into(),
        0x0025 => "percent".into(),
        0x0026 => "ampersand".into(),
        0x0027 => "quotesingle".into(),
        0x0028 => "parenleft".into(),
        0x0029 => "parenright".into(),
        0x002A => "asterisk".into(),
        0x002B => "plus".into(),
        0x002C => "comma".into(),
        0x002D => "hyphen".into(),
        0x002E => "period".into(),
        0x002F => "slash".into(),
        0x0030 => "zero".into(),
        0x0031 => "one".into(),
        0x0032 => "two".into(),
        0x0033 => "three".into(),
        0x0034 => "four".into(),
        0x0035 => "five".into(),
        0x0036 => "six".into(),
        0x0037 => "seven".into(),
        0x0038 => "eight".into(),
        0x0039 => "nine".into(),
        0x003A => "colon".into(),
        0x003B => "semicolon".into(),
        0x003C => "less".into(),
        0x003D => "equal".into(),
        0x003E => "greater".into(),
        0x003F => "question".into(),
        0x0040 => "at".into(),
        0x0041..=0x005A => char::from_u32(cp).unwrap().to_string(), // A–Z
        0x005B => "bracketleft".into(),
        0x005C => "backslash".into(),
        0x005D => "bracketright".into(),
        0x005E => "asciicircum".into(),
        0x005F => "underscore".into(),
        0x0060 => "grave".into(),
        0x0061..=0x007A => char::from_u32(cp).unwrap().to_string(), // a–z
        0x007B => "braceleft".into(),
        0x007C => "bar".into(),
        0x007D => "braceright".into(),
        0x007E => "asciitilde".into(),
        0x00A1 => "exclamdown".into(),
        0x00A2 => "cent".into(),
        0x00A3 => "sterling".into(),
        0x00A4 => "currency".into(),
        0x00A5 => "yen".into(),
        0x00A6 => "brokenbar".into(),
        0x00A7 => "section".into(),
        0x00A8 => "dieresis".into(),
        0x00A9 => "copyright".into(),
        0x00AA => "ordfeminine".into(),
        0x00AB => "guillemotleft".into(),
        0x00AC => "logicalnot".into(),
        0x00AE => "registered".into(),
        0x00AF => "macron".into(),
        0x00B0 => "degree".into(),
        0x00B1 => "plusminus".into(),
        0x00B2 => "twosuperior".into(),
        0x00B3 => "threesuperior".into(),
        0x00B4 => "acute".into(),
        0x00B5 => "mu".into(),
        0x00B6 => "paragraph".into(),
        0x00B7 => "periodcentered".into(),
        0x00B8 => "cedilla".into(),
        0x00B9 => "onesuperior".into(),
        0x00BA => "ordmasculine".into(),
        0x00BB => "guillemotright".into(),
        0x00BC => "onequarter".into(),
        0x00BD => "onehalf".into(),
        0x00BE => "threequarters".into(),
        0x00BF => "questiondown".into(),
        0x00C0 => "Agrave".into(),
        0x00C1 => "Aacute".into(),
        0x00C2 => "Acircumflex".into(),
        0x00C3 => "Atilde".into(),
        0x00C4 => "Adieresis".into(),
        0x00C5 => "Aring".into(),
        0x00C6 => "AE".into(),
        0x00C7 => "Ccedilla".into(),
        0x00C8 => "Egrave".into(),
        0x00C9 => "Eacute".into(),
        0x00CA => "Ecircumflex".into(),
        0x00CB => "Edieresis".into(),
        0x00CC => "Igrave".into(),
        0x00CD => "Iacute".into(),
        0x00CE => "Icircumflex".into(),
        0x00CF => "Idieresis".into(),
        0x00D0 => "Eth".into(),
        0x00D1 => "Ntilde".into(),
        0x00D2 => "Ograve".into(),
        0x00D3 => "Oacute".into(),
        0x00D4 => "Ocircumflex".into(),
        0x00D5 => "Otilde".into(),
        0x00D6 => "Odieresis".into(),
        0x00D7 => "multiply".into(),
        0x00D8 => "Oslash".into(),
        0x00D9 => "Ugrave".into(),
        0x00DA => "Uacute".into(),
        0x00DB => "Ucircumflex".into(),
        0x00DC => "Udieresis".into(),
        0x00DD => "Yacute".into(),
        0x00DE => "Thorn".into(),
        0x00DF => "germandbls".into(),
        0x00E0 => "agrave".into(),
        0x00E1 => "aacute".into(),
        0x00E2 => "acircumflex".into(),
        0x00E3 => "atilde".into(),
        0x00E4 => "adieresis".into(),
        0x00E5 => "aring".into(),
        0x00E6 => "ae".into(),
        0x00E7 => "ccedilla".into(),
        0x00E8 => "egrave".into(),
        0x00E9 => "eacute".into(),
        0x00EA => "ecircumflex".into(),
        0x00EB => "edieresis".into(),
        0x00EC => "igrave".into(),
        0x00ED => "iacute".into(),
        0x00EE => "icircumflex".into(),
        0x00EF => "idieresis".into(),
        0x00F0 => "eth".into(),
        0x00F1 => "ntilde".into(),
        0x00F2 => "ograve".into(),
        0x00F3 => "oacute".into(),
        0x00F4 => "ocircumflex".into(),
        0x00F5 => "otilde".into(),
        0x00F6 => "odieresis".into(),
        0x00F7 => "divide".into(),
        0x00F8 => "oslash".into(),
        0x00F9 => "ugrave".into(),
        0x00FA => "uacute".into(),
        0x00FB => "ucircumflex".into(),
        0x00FC => "udieresis".into(),
        0x00FD => "yacute".into(),
        0x00FE => "thorn".into(),
        0x00FF => "ydieresis".into(),
        0x0131 => "dotlessi".into(),
        0x0141 => "Lslash".into(),
        0x0142 => "lslash".into(),
        0x0152 => "OE".into(),
        0x0153 => "oe".into(),
        0x0160 => "Scaron".into(),
        0x0161 => "scaron".into(),
        0x0178 => "Ydieresis".into(),
        0x017D => "Zcaron".into(),
        0x017E => "zcaron".into(),
        0x0192 => "florin".into(),
        0x02C6 => "circumflex".into(),
        0x02DC => "tilde".into(),
        0x2013 => "endash".into(),
        0x2014 => "emdash".into(),
        0x2018 => "quoteleft".into(),
        0x2019 => "quoteright".into(),
        0x201A => "quotesinglbase".into(),
        0x201C => "quotedblleft".into(),
        0x201D => "quotedblright".into(),
        0x201E => "quotedblbase".into(),
        0x2020 => "dagger".into(),
        0x2021 => "daggerdbl".into(),
        0x2022 => "bullet".into(),
        0x2026 => "ellipsis".into(),
        0x2030 => "perthousand".into(),
        0x2039 => "guilsinglleft".into(),
        0x203A => "guilsinglright".into(),
        0x20AC => "Euro".into(),
        0x2122 => "trademark".into(),
        0xFB01 => "fi".into(),
        0xFB02 => "fl".into(),
        _ if cp <= 0xFFFF => format!("uni{:04X}", cp),
        _ => format!("u{:05X}", cp),
    }
}
